// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package bpfobjs

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type AgentCgroupConfig struct {
	_                  structs.HostLayout
	EnforcementMode    uint8
	ExecDefaultAllow   uint8
	FileDefaultAllow   uint8
	NetDefaultAllow    uint8
	DeviceDefaultAllow uint8
	BenchmarkMode      uint8
	Pad                [2]uint8
}

type AgentEvent struct {
	_           structs.HostLayout
	CgroupId    uint64
	TimestampNs uint64
	Pid         uint32
	Tgid        uint32
	Type        uint8
	Decision    uint8
	HookMode    uint8
	Pad0        uint8
	DestAddrV4  uint32
	DestPort    uint16
	Pad1        [2]uint8
	Path        [256]int8
	_           [4]byte
}

type AgentNetRuleKey struct {
	_          structs.HostLayout
	CgroupId   uint64
	DestAddrV4 uint32
	DestPort   uint16
	Pad        uint16
}

type AgentPathRuleKey struct {
	_        structs.HostLayout
	CgroupId uint64
	PathHash uint64
}

type AgentRuleAction struct {
	_     structs.HostLayout
	Allow uint8
	Pad   [7]uint8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	AgentMapBpfLockEngaged = "bpf_lock_engaged"
	AgentMapCgroupConfigs  = "cgroup_configs"
	AgentMapEventCounters  = "event_counters"
	AgentMapEvents         = "events"
	AgentMapExecRules      = "exec_rules"
	AgentMapFileRules      = "file_rules"
	AgentMapNetRules       = "net_rules"
	AgentProgLsmBpfLock    = "lsm_bpf_lock"
	AgentProgLsmConnect    = "lsm_connect"
	AgentProgLsmExec       = "lsm_exec"
	AgentProgLsmFileOpen   = "lsm_file_open"
	AgentProgTraceConnect  = "trace_connect"
	AgentProgTraceExecve   = "trace_execve"
	AgentProgTraceOpen     = "trace_open"
	AgentProgTraceOpenat   = "trace_openat"
	AgentVarUnusedEvent    = "unused_event"
)

// LoadAgent returns the embedded CollectionSpec for Agent.
func LoadAgent() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_AgentBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Agent: %w", err)
	}

	return spec, err
}

// LoadAgentObjects loads Agent and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*AgentObjects
//	*AgentPrograms
//	*AgentMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadAgentObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadAgent()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// AgentSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type AgentSpecs struct {
	AgentProgramSpecs
	AgentMapSpecs
	AgentVariableSpecs
}

// AgentProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type AgentProgramSpecs struct {
	LsmBpfLock   *ebpf.ProgramSpec `ebpf:"lsm_bpf_lock"`
	LsmConnect   *ebpf.ProgramSpec `ebpf:"lsm_connect"`
	LsmExec      *ebpf.ProgramSpec `ebpf:"lsm_exec"`
	LsmFileOpen  *ebpf.ProgramSpec `ebpf:"lsm_file_open"`
	TraceConnect *ebpf.ProgramSpec `ebpf:"trace_connect"`
	TraceExecve  *ebpf.ProgramSpec `ebpf:"trace_execve"`
	TraceOpen    *ebpf.ProgramSpec `ebpf:"trace_open"`
	TraceOpenat  *ebpf.ProgramSpec `ebpf:"trace_openat"`
}

// AgentMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type AgentMapSpecs struct {
	BpfLockEngaged *ebpf.MapSpec `ebpf:"bpf_lock_engaged"`
	CgroupConfigs  *ebpf.MapSpec `ebpf:"cgroup_configs"`
	EventCounters  *ebpf.MapSpec `ebpf:"event_counters"`
	Events         *ebpf.MapSpec `ebpf:"events"`
	ExecRules      *ebpf.MapSpec `ebpf:"exec_rules"`
	FileRules      *ebpf.MapSpec `ebpf:"file_rules"`
	NetRules       *ebpf.MapSpec `ebpf:"net_rules"`
}

// AgentVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type AgentVariableSpecs struct {
	UnusedEvent *ebpf.VariableSpec `ebpf:"unused_event"`
}

// AgentObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadAgentObjects or ebpf.CollectionSpec.LoadAndAssign.
type AgentObjects struct {
	AgentPrograms
	AgentMaps
	AgentVariables
}

func (o *AgentObjects) Close() error {
	return _AgentClose(
		&o.AgentPrograms,
		&o.AgentMaps,
	)
}

// AgentMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadAgentObjects or ebpf.CollectionSpec.LoadAndAssign.
type AgentMaps struct {
	BpfLockEngaged *ebpf.Map `ebpf:"bpf_lock_engaged"`
	CgroupConfigs  *ebpf.Map `ebpf:"cgroup_configs"`
	EventCounters  *ebpf.Map `ebpf:"event_counters"`
	Events         *ebpf.Map `ebpf:"events"`
	ExecRules      *ebpf.Map `ebpf:"exec_rules"`
	FileRules      *ebpf.Map `ebpf:"file_rules"`
	NetRules       *ebpf.Map `ebpf:"net_rules"`
}

func (m *AgentMaps) Close() error {
	return _AgentClose(
		m.BpfLockEngaged,
		m.CgroupConfigs,
		m.EventCounters,
		m.Events,
		m.ExecRules,
		m.FileRules,
		m.NetRules,
	)
}

// AgentVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadAgentObjects or ebpf.CollectionSpec.LoadAndAssign.
type AgentVariables struct {
	UnusedEvent *ebpf.Variable `ebpf:"unused_event"`
}

// AgentPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadAgentObjects or ebpf.CollectionSpec.LoadAndAssign.
type AgentPrograms struct {
	LsmBpfLock   *ebpf.Program `ebpf:"lsm_bpf_lock"`
	LsmConnect   *ebpf.Program `ebpf:"lsm_connect"`
	LsmExec      *ebpf.Program `ebpf:"lsm_exec"`
	LsmFileOpen  *ebpf.Program `ebpf:"lsm_file_open"`
	TraceConnect *ebpf.Program `ebpf:"trace_connect"`
	TraceExecve  *ebpf.Program `ebpf:"trace_execve"`
	TraceOpen    *ebpf.Program `ebpf:"trace_open"`
	TraceOpenat  *ebpf.Program `ebpf:"trace_openat"`
}

func (p *AgentPrograms) Close() error {
	return _AgentClose(
		p.LsmBpfLock,
		p.LsmConnect,
		p.LsmExec,
		p.LsmFileOpen,
		p.TraceConnect,
		p.TraceExecve,
		p.TraceOpen,
		p.TraceOpenat,
	)
}

func _AgentClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed agent_x86_bpfel.o
var _AgentBytes []byte
