// Package bpfobjs holds the Go bindings generated by bpf2go from
// bpf/agent.bpf.c. Run `go generate ./...` from the ebpf-agent module root
// after changing the C source (requires clang, llvm, and libbpf headers —
// see EXPERIMENTS_LOG.md Phase 4 for the exact local toolchain versions used).
package bpfobjs

//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -cc clang -target amd64 -type event -type cgroup_config -type path_rule_key -type net_rule_key -type rule_action Agent ../../bpf/agent.bpf.c -- -I../../bpf -I../../bpf/headers -O2 -g -D__TARGET_ARCH_x86
