#!/usr/bin/env bash
# Generates a fresh Ed25519 key pair for local kind testing, applies the
# public half as the trust-anchor ConfigMap the Runtime Guard Operator reads,
# and writes the private half to a local, git-ignored env file for use by
# test/smoke-test tooling that needs to mint a signed test placement token
# (Phase 5). Never used against a real cluster: real deployments trust
# article 1's actual scheduler key, not a key generated by this script.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OPERATOR_DIR="$(cd "$SCRIPT_DIR/../../operator" && pwd)"
KUBE_CONTEXT="${KUBE_CONTEXT:-kind-article2}"
NAMESPACE="${TRUST_ANCHOR_NAMESPACE:-aiops-system}"
CONFIGMAP_NAME="${TRUST_ANCHOR_CONFIGMAP_NAME:-attestation-scheduler-public-key}"
CONFIGMAP_KEY="${TRUST_ANCHOR_CONFIGMAP_KEY:-publicKeyHex}"
ENV_FILE="$SCRIPT_DIR/trust-anchor.env"

echo "Generating fresh Ed25519 test key pair..."
KEYS_OUTPUT="$(cd "$OPERATOR_DIR" && go run ./cmd/gen-keypair)"
PUBLIC_KEY_HEX="$(echo "$KEYS_OUTPUT" | grep '^PUBLIC_KEY_HEX=' | cut -d= -f2)"
PRIVATE_KEY_HEX="$(echo "$KEYS_OUTPUT" | grep '^PRIVATE_KEY_HEX=' | cut -d= -f2)"

if [[ -z "$PUBLIC_KEY_HEX" || -z "$PRIVATE_KEY_HEX" ]]; then
  echo "failed to generate key pair" >&2
  exit 1
fi

echo "Applying namespace '$NAMESPACE' and trust-anchor ConfigMap '$CONFIGMAP_NAME' to context '$KUBE_CONTEXT'..."
kubectl --context "$KUBE_CONTEXT" apply -f "$SCRIPT_DIR/namespace.yaml"
kubectl --context "$KUBE_CONTEXT" create configmap "$CONFIGMAP_NAME" \
  --namespace "$NAMESPACE" \
  --from-literal="$CONFIGMAP_KEY=$PUBLIC_KEY_HEX" \
  --dry-run=client -o yaml | kubectl --context "$KUBE_CONTEXT" apply -f -

cat > "$ENV_FILE" <<EOF
# Generated by gen-trust-anchor.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ) — DO NOT COMMIT.
# Test-only Ed25519 key pair for the kind-article2 cluster's trust anchor.
TRUST_ANCHOR_PUBLIC_KEY_HEX=$PUBLIC_KEY_HEX
TRUST_ANCHOR_PRIVATE_KEY_HEX=$PRIVATE_KEY_HEX
EOF
echo "Private key (test-only) written to $ENV_FILE (git-ignored)."
