//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentIntegrityObserved) DeepCopyInto(out *AgentIntegrityObserved) {
	*out = *in
	if in.RTMRIndex != nil {
		in, out := &in.RTMRIndex, &out.RTMRIndex
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentIntegrityObserved.
func (in *AgentIntegrityObserved) DeepCopy() *AgentIntegrityObserved {
	if in == nil {
		return nil
	}
	out := new(AgentIntegrityObserved)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentIntegritySpec) DeepCopyInto(out *AgentIntegritySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentIntegritySpec.
func (in *AgentIntegritySpec) DeepCopy() *AgentIntegritySpec {
	if in == nil {
		return nil
	}
	out := new(AgentIntegritySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BPFLockSpec) DeepCopyInto(out *BPFLockSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BPFLockSpec.
func (in *BPFLockSpec) DeepCopy() *BPFLockSpec {
	if in == nil {
		return nil
	}
	out := new(BPFLockSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceAccessPolicy) DeepCopyInto(out *DeviceAccessPolicy) {
	*out = *in
	if in.AllowedDevicePaths != nil {
		in, out := &in.AllowedDevicePaths, &out.AllowedDevicePaths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceAccessPolicy.
func (in *DeviceAccessPolicy) DeepCopy() *DeviceAccessPolicy {
	if in == nil {
		return nil
	}
	out := new(DeviceAccessPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvidenceSignature) DeepCopyInto(out *EvidenceSignature) {
	*out = *in
	in.IssuedAt.DeepCopyInto(&out.IssuedAt)
	in.ExpiresAt.DeepCopyInto(&out.ExpiresAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvidenceSignature.
func (in *EvidenceSignature) DeepCopy() *EvidenceSignature {
	if in == nil {
		return nil
	}
	out := new(EvidenceSignature)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecPolicy) DeepCopyInto(out *ExecPolicy) {
	*out = *in
	if in.AllowedPaths != nil {
		in, out := &in.AllowedPaths, &out.AllowedPaths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DeniedPaths != nil {
		in, out := &in.DeniedPaths, &out.DeniedPaths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecPolicy.
func (in *ExecPolicy) DeepCopy() *ExecPolicy {
	if in == nil {
		return nil
	}
	out := new(ExecPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileAccessPolicy) DeepCopyInto(out *FileAccessPolicy) {
	*out = *in
	if in.AllowedPathPrefixes != nil {
		in, out := &in.AllowedPathPrefixes, &out.AllowedPathPrefixes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DeniedPathPrefixes != nil {
		in, out := &in.DeniedPathPrefixes, &out.DeniedPathPrefixes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileAccessPolicy.
func (in *FileAccessPolicy) DeepCopy() *FileAccessPolicy {
	if in == nil {
		return nil
	}
	out := new(FileAccessPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkEgressPolicy) DeepCopyInto(out *NetworkEgressPolicy) {
	*out = *in
	if in.AllowedCIDRs != nil {
		in, out := &in.AllowedCIDRs, &out.AllowedCIDRs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedPorts != nil {
		in, out := &in.AllowedPorts, &out.AllowedPorts
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
	if in.DeniedCIDRs != nil {
		in, out := &in.DeniedCIDRs, &out.DeniedCIDRs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkEgressPolicy.
func (in *NetworkEgressPolicy) DeepCopy() *NetworkEgressPolicy {
	if in == nil {
		return nil
	}
	out := new(NetworkEgressPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectReference) DeepCopyInto(out *ObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectReference.
func (in *ObjectReference) DeepCopy() *ObjectReference {
	if in == nil {
		return nil
	}
	out := new(ObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservedBehaviorCounters) DeepCopyInto(out *ObservedBehaviorCounters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservedBehaviorCounters.
func (in *ObservedBehaviorCounters) DeepCopy() *ObservedBehaviorCounters {
	if in == nil {
		return nil
	}
	out := new(ObservedBehaviorCounters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementBinding) DeepCopyInto(out *PlacementBinding) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementBinding.
func (in *PlacementBinding) DeepCopy() *PlacementBinding {
	if in == nil {
		return nil
	}
	out := new(PlacementBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyDerivationTrace) DeepCopyInto(out *PolicyDerivationTrace) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyDerivationTrace.
func (in *PolicyDerivationTrace) DeepCopy() *PolicyDerivationTrace {
	if in == nil {
		return nil
	}
	out := new(PolicyDerivationTrace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimePlacementEvidence) DeepCopyInto(out *RuntimePlacementEvidence) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimePlacementEvidence.
func (in *RuntimePlacementEvidence) DeepCopy() *RuntimePlacementEvidence {
	if in == nil {
		return nil
	}
	out := new(RuntimePlacementEvidence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RuntimePlacementEvidence) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimePlacementEvidenceList) DeepCopyInto(out *RuntimePlacementEvidenceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RuntimePlacementEvidence, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimePlacementEvidenceList.
func (in *RuntimePlacementEvidenceList) DeepCopy() *RuntimePlacementEvidenceList {
	if in == nil {
		return nil
	}
	out := new(RuntimePlacementEvidenceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RuntimePlacementEvidenceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimePlacementEvidenceSpec) DeepCopyInto(out *RuntimePlacementEvidenceSpec) {
	*out = *in
	out.PolicyRef = in.PolicyRef
	out.TargetRef = in.TargetRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimePlacementEvidenceSpec.
func (in *RuntimePlacementEvidenceSpec) DeepCopy() *RuntimePlacementEvidenceSpec {
	if in == nil {
		return nil
	}
	out := new(RuntimePlacementEvidenceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimePlacementEvidenceStatus) DeepCopyInto(out *RuntimePlacementEvidenceStatus) {
	*out = *in
	in.LastHeartbeat.DeepCopyInto(&out.LastHeartbeat)
	in.AgentIntegrity.DeepCopyInto(&out.AgentIntegrity)
	out.Behavior = in.Behavior
	if in.LastViolation != nil {
		in, out := &in.LastViolation, &out.LastViolation
		*out = new(ViolationRecord)
		(*in).DeepCopyInto(*out)
	}
	if in.RevokedAt != nil {
		in, out := &in.RevokedAt, &out.RevokedAt
		*out = (*in).DeepCopy()
	}
	in.LastAuthorizationSync.DeepCopyInto(&out.LastAuthorizationSync)
	in.Signature.DeepCopyInto(&out.Signature)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimePlacementEvidenceStatus.
func (in *RuntimePlacementEvidenceStatus) DeepCopy() *RuntimePlacementEvidenceStatus {
	if in == nil {
		return nil
	}
	out := new(RuntimePlacementEvidenceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeSecurityPolicy) DeepCopyInto(out *RuntimeSecurityPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeSecurityPolicy.
func (in *RuntimeSecurityPolicy) DeepCopy() *RuntimeSecurityPolicy {
	if in == nil {
		return nil
	}
	out := new(RuntimeSecurityPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RuntimeSecurityPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeSecurityPolicyList) DeepCopyInto(out *RuntimeSecurityPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RuntimeSecurityPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeSecurityPolicyList.
func (in *RuntimeSecurityPolicyList) DeepCopy() *RuntimeSecurityPolicyList {
	if in == nil {
		return nil
	}
	out := new(RuntimeSecurityPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RuntimeSecurityPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeSecurityPolicySpec) DeepCopyInto(out *RuntimeSecurityPolicySpec) {
	*out = *in
	out.PlacementDecisionRef = in.PlacementDecisionRef
	out.TargetRef = in.TargetRef
	out.Binding = in.Binding
	in.Exec.DeepCopyInto(&out.Exec)
	in.FileAccess.DeepCopyInto(&out.FileAccess)
	in.NetworkEgress.DeepCopyInto(&out.NetworkEgress)
	in.DeviceAccess.DeepCopyInto(&out.DeviceAccess)
	out.AgentIntegrity = in.AgentIntegrity
	out.Derivation = in.Derivation
	out.BPFLock = in.BPFLock
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeSecurityPolicySpec.
func (in *RuntimeSecurityPolicySpec) DeepCopy() *RuntimeSecurityPolicySpec {
	if in == nil {
		return nil
	}
	out := new(RuntimeSecurityPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeSecurityPolicyStatus) DeepCopyInto(out *RuntimeSecurityPolicyStatus) {
	*out = *in
	if in.EnforcementReadyAt != nil {
		in, out := &in.EnforcementReadyAt, &out.EnforcementReadyAt
		*out = (*in).DeepCopy()
	}
	if in.EnforcementReadyMonotonicNs != nil {
		in, out := &in.EnforcementReadyMonotonicNs, &out.EnforcementReadyMonotonicNs
		*out = new(int64)
		**out = **in
	}
	if in.FirstObservedOperationMonotonicNs != nil {
		in, out := &in.FirstObservedOperationMonotonicNs, &out.FirstObservedOperationMonotonicNs
		*out = new(int64)
		**out = **in
	}
	if in.AppliedCgroupIDs != nil {
		in, out := &in.AppliedCgroupIDs, &out.AppliedCgroupIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeSecurityPolicyStatus.
func (in *RuntimeSecurityPolicyStatus) DeepCopy() *RuntimeSecurityPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(RuntimeSecurityPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ViolationRecord) DeepCopyInto(out *ViolationRecord) {
	*out = *in
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ViolationRecord.
func (in *ViolationRecord) DeepCopy() *ViolationRecord {
	if in == nil {
		return nil
	}
	out := new(ViolationRecord)
	in.DeepCopyInto(out)
	return out
}
