apiVersion: v1
kind: Namespace
metadata:
  name: runtime-guard-operator-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: runtime-guard-agent-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: aiops-system
