# permissions for end users to edit runtimesecuritypolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: runtimesecuritypolicy-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: runtime-guard-operator
    app.kubernetes.io/part-of: runtime-guard-operator
    app.kubernetes.io/managed-by: kustomize
  name: runtimesecuritypolicy-editor-role
rules:
- apiGroups:
  - aiops.imperium.io
  resources:
  - runtimesecuritypolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aiops.imperium.io
  resources:
  - runtimesecuritypolicies/status
  verbs:
  - get
